version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: cron
      cronjob: '0 12 * * *'
      timezone: America/Detroit
    commit-message:
      prefix: chore

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns: ['*']
    multi-ecosystem-group: dependencies

  - package-ecosystem: npm
    directory: /
    patterns: ['*']
    multi-ecosystem-group: dependencies
    ignore:
      - dependency-name: '@types/node'
        versions: ['>=25.0.0']
