version: 2

registries:
  npm:
    type: npm-registry
    url: https://registry.npmjs.org
    token: unused # required field

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: cron
      cronjob: '0 12 * * *'
      timezone: America/Detroit
    commit-message:
      prefix: chore

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns: ['*']
    multi-ecosystem-group: dependencies
    cooldown:
      default-days: 1

  - package-ecosystem: npm
    directory: /
    patterns: ['*']
    multi-ecosystem-group: dependencies
    registries:
      - npm
    cooldown:
      default-days: 1
    ignore:
      - dependency-name: '@types/node'
        versions: ['>=25.0.0']
