packages:
  - packages/*

blockExoticSubdeps: true

catalog:
  '@hono/node-server': ^1.19.14
  '@hono/zod-validator': ^0.7.6
  '@libsql/client': ^0.17.2
  '@tsconfig/node-ts': 23.6.4
  '@tsconfig/node24': 24.0.4
  '@tsconfig/strictest': 2.0.8
  '@types/node': 24.12.2
  drizzle-kit: 0.31.10
  drizzle-orm: ^0.45.2
  drizzle-zod: ^0.8.3
  hono: ^4.12.14
  husky: 9.1.7
  lint-staged: 16.4.0
  oxfmt: 0.47.0
  oxlint: 1.62.0
  oxlint-tsgolint: 0.22.1
  typescript: 6.0.3
  vitest: 4.1.4
  zod: ^4.3.6

catalogMode: strict

minimumReleaseAge: 1440

overrides:
  esbuild: '>=0.28.0'
