packages:
  - packages/*

blockExoticSubdeps: true

catalog:
  '@eslint/js': 9.39.2
  '@hono/node-server': ^1.19.9
  '@libsql/client': ^0.17.0
  '@tsconfig/node-ts': 23.6.2
  '@tsconfig/node24': 24.0.3
  '@tsconfig/strictest': 2.0.8
  '@types/node': 24.10.8
  drizzle-kit: 0.31.9
  drizzle-orm: ^0.45.1
  eslint: 9.39.2
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-import: 2.32.0
  globals: 17.0.0
  hono: ^4.11.7
  husky: 9.1.7
  lint-staged: 16.2.7
  prettier: 3.8.0
  typescript: 5.9.3
  typescript-eslint: 8.53.0
  vitest: 4.0.18
  zod: ^4.3.5

catalogMode: strict

minimumReleaseAge: 1440

overrides:
  esbuild: '>=0.27.3'
