import type { LogRow } from '@localsink/contract';

// Deterministic sample logs typed against the real wire contract (LogRow):
// epoch-ms timestamps, object attributes, and object errors with a joined
// stack string. Drives the UI until the real /api/logs wiring lands.

const BASE_TS = Date.UTC(2026, 5, 27, 16, 20, 27, 407);
const STEP_MS = 47_000;

type Seed = Omit<LogRow, 'id' | 'timestamp'>;

const seeds: Seed[] = [
  {
    service_name: 'api',
    level: 'info',
    message: 'GET /health 200',
    logger: 'pino',
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { method: 'GET', status: 200, dur_ms: 3 },
  },
  {
    service_name: 'api',
    level: 'debug',
    message: 'route matched',
    logger: 'pino',
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { route: '/users/:id', handler: 'getUser', cache: 'miss' },
  },
  {
    service_name: 'api',
    level: 'info',
    message: 'GET /users/42 200',
    logger: 'pino',
    trace_id: '4f9a2b7c0e1d3a55',
    span_id: null,
    error: null,
    attributes: { method: 'GET', status: 200, dur_ms: 28, user_id: 'usr_42' },
  },
  {
    service_name: 'api',
    level: 'warn',
    message: 'slow query detected',
    logger: 'pino',
    trace_id: null,
    span_id: null,
    error: null,
    attributes: {
      dur_ms: 1840,
      threshold_ms: 500,
      query: 'SELECT * FROM events WHERE tenant_id = $1',
      rows: 18402,
    },
  },
  {
    service_name: 'api',
    level: 'error',
    message:
      'unhandled exception while processing POST /orders for tenant acme',
    logger: 'pino',
    trace_id: '4f9a2b7c0e1d3a55',
    span_id: null,
    error: {
      type: 'TypeError',
      message: "Cannot read properties of undefined (reading 'id')",
      stack: [
        "TypeError: Cannot read properties of undefined (reading 'id')",
        '    at handler (/srv/api/routes/orders.js:88:24)',
        '    at process (/srv/api/middleware/wrap.js:31:9)',
        '    at async Server.<anonymous> (/srv/api/server.js:204:5)',
      ].join('\n'),
    },
    attributes: { req_id: 'r_8fa3', route: 'POST /orders', status: 500 },
  },
  {
    service_name: 'auth',
    level: 'info',
    message: 'user login succeeded',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { user_id: 'usr_9', method: 'password', ip: '10.0.0.14' },
  },
  {
    service_name: 'auth',
    level: 'warn',
    message: 'login throttled',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { user_id: 'usr_9', attempts: 5, window_s: 60 },
  },
  {
    service_name: 'auth',
    level: 'error',
    message: 'token verification failed',
    logger: null,
    trace_id: null,
    span_id: null,
    error: { type: 'JWTExpired', message: 'jwt expired' },
    attributes: {
      user_id: 'usr_9',
      token_age_s: 3700,
      iss: 'localsink.auth',
      kid: 'k_2026_03',
    },
  },
  {
    service_name: 'worker',
    level: 'trace',
    message: 'span start: reindex',
    logger: null,
    trace_id: 'a1b2c3d4e5f60718',
    span_id: null,
    error: null,
    attributes: { span: 'reindex', parent: null },
  },
  {
    service_name: 'worker',
    level: 'info',
    message: 'job started',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { job: 'reindex', queue: 'default', job_id: 'j_1042' },
  },
  {
    service_name: 'worker',
    level: 'info',
    message: 'job completed',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { job: 'reindex', dur_ms: 5120, job_id: 'j_1042' },
  },
  {
    service_name: 'worker',
    level: 'warn',
    message: 'job retrying',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { job: 'email.send', attempt: 2, backoff_ms: 4000 },
  },
  {
    service_name: 'worker',
    level: 'error',
    message: 'job failed after 3 retries',
    logger: null,
    trace_id: null,
    span_id: null,
    error: {
      type: 'Error',
      message: 'ECONNREFUSED 127.0.0.1:6379',
      stack: [
        'Error: ECONNREFUSED 127.0.0.1:6379',
        '    at TCPConnectWrap.afterConnect (node:net:1595:16)',
        '    at RedisClient.connect (/srv/worker/lib/redis.js:42:11)',
      ].join('\n'),
    },
    attributes: { job: 'email.send', job_id: 'j_1043', attempts: 3 },
  },
  {
    service_name: 'payments',
    level: 'info',
    message: 'charge created',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { amount: 4200, currency: 'usd', charge_id: 'ch_77b' },
  },
  {
    service_name: 'payments',
    level: 'error',
    message: 'charge declined',
    logger: null,
    trace_id: null,
    span_id: null,
    error: { type: 'CardError', message: 'card_declined' },
    attributes: {
      charge_id: 'ch_78c',
      code: 'card_declined',
      decline_reason: 'insufficient_funds',
      amount: 9900,
      currency: 'usd',
    },
  },
  {
    service_name: 'web',
    level: 'info',
    message: 'page rendered /dashboard',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { route: '/dashboard', dur_ms: 64, status: 200 },
  },
  {
    service_name: 'web',
    level: 'debug',
    message: 'cache hit',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { key: 'dash:usr_42', ttl_s: 30 },
  },
  {
    service_name: 'billing-reconciliation-worker',
    level: 'info',
    message: 'reconciliation batch complete',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: { batch_id: 'rb_5512', entries: 1284, dur_ms: 8810 },
  },
  {
    service_name: 'billing-reconciliation-worker',
    level: 'warn',
    message: 'ledger mismatch detected',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: {
      account_id: 'acct_8841',
      expected_cents: 128400,
      actual_cents: 128050,
      delta_cents: 350,
      batch_id: 'rb_5512',
      currency: 'usd',
    },
  },
  // Non-canonical levels — exercise dynamic level coloring:
  // `fatal` snaps to the error severity; `audit` is unrecognized and gets a
  // palette slot. Both render with their raw label.
  {
    service_name: 'payments',
    level: 'fatal',
    message: 'database connection pool exhausted; shutting down',
    logger: 'pino',
    trace_id: '4f9a2b7c0e1d3a55',
    span_id: null,
    error: {
      type: 'PoolExhaustedError',
      message: 'timed out acquiring a connection from the pool',
      stack: [
        'PoolExhaustedError: timed out acquiring a connection from the pool',
        '    at Pool.acquire (/srv/payments/db/pool.js:74:13)',
        '    at async charge (/srv/payments/charge.js:31:5)',
      ].join('\n'),
    },
    attributes: { pool_size: 20, waiting: 47, timeout_ms: 5000 },
  },
  {
    service_name: 'auth',
    level: 'audit',
    message: 'role granted: admin to usr_9',
    logger: null,
    trace_id: null,
    span_id: null,
    error: null,
    attributes: {
      actor: 'usr_1',
      target: 'usr_9',
      role: 'admin',
      via: 'console',
    },
  },
];

export const sampleLogs: LogRow[] = seeds.map((seed, index) => ({
  ...seed,
  id: index + 1,
  timestamp: BASE_TS + index * STEP_MS,
}));
